services:
  # A Docker web service
  - type: web
    name: nocodb
    env: docker
    dockerfilePath: "./nocodb/Dockerfile"
    region: oregon # optional (defaults to oregon)
    healthCheckPath: /dashboard
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myappdbname
          property: connectionString
      - key: PORT
        value: 8080
  - type: web
    name: minio
    env: docker
    dockerfilePath: ./minio/Dockerfile
    dockerContext: ./minio
    disk:
      name: data
      mountPath: /data
    healthCheckPath: /minio/health/live
    envVars:
      - key: MINIO_ROOT_USER
        generateValue: true
      - key: MINIO_ROOT_PASSWORD
        generateValue: true
      - key: PORT
        value: 10000
databases:
  - name: myappdbname
    user: myappuser